### PR TITLE
Use text_box to draw elements in a comb field.

### PR DESCRIPTION
**Pull request by yilangmok-gusto**
Previously comb field was drawn using a table, which throws exceptions when the characters don't fit. Using text_box with (overflow: shrink_to_fit) ensures that characters always fit within the table. When there is too many characters, it ignores the combs and just draws a normal text box.

### CODE REVIEW

**Comment by yilangmok-gusto** [comment]
Hi Bo, I have an urgent check-in that requires this change. Can you please take a look?  Thanks!

**Comment by bss** [comment]
Why would you want add additional characters into a combed text field? Throwing the exception is correct, it's a comb, it can only contain that amount of characters.

**Comment by yilangmok-gusto** [comment]
There are 2 different issues:
1. When there is not enough space in the bounding box to fit a character, Prawn currently throws CannotFit exception. I changed it to text_box so that the character is guaranteed to be drawn. I think this is a good change.
2. There are many forms which have comb fields for e.g. Address, but the address often doesn't fit. Instead of throwing an exception, we should try to fit it anyways (comb is best-effort). I think this is the correct behavior for enrollment forms, but I'm wondering if this is bad for tax forms. Is there a way to compromise?

In case #2, how should Ops handle this? I suspect they'll do the same thing and ignore the comb.

**Comment by bss** [comment]
Have you seen the issue where there wasn't enough space if the font size was set correctly for the field in the template?
It sounds like those fields shouldn't really have a comb in the first place?

**Comment by yilangmok-gusto** [comment]
As per our discussion, Prawn::FillForm will throw an exception if the value is too long for a comb field. If allow_comb_overflow: true is passed in, the field will be drawn as a simple text box.  Thanks!

**Comment by bss** [comment]
Looks great, thanks! @zp-alfred accept.

**Comment by zp-alfred** [comment]
Accepted by bss!

**Comment by yilangmok-gusto** [comment]
Awesome, thanks Bo!

**Pull request closed without merging**
